import {
  FaWarehouse,
  FaDollarSign,
  FaShoppingCart,
  FaChartLine,
  FaClipboardList,
  FaWallet,
  FaRegUserCircle,
  FaFileInvoice,
  FaRegUser,
} from "react-icons/fa";
import { Category, IconColors } from "./models";

export const Categories: Category[] = [
  {
    id: 1,
    title: "Purchase",
    Icon: FaShoppingCart,
    textColor: undefined,
    backgroundColor: undefined,
    iconColor: IconColors.SUCCESS,
    url: "/purchase",
    subcategory: [
      {
        id: 1,
        title: "Supplier",
        Icon: FaRegUser,
        textColor: undefined,
        backgroundColor: undefined,
        iconColor: IconColors.SUCCESS,
        url: "/purchase/suppliers",
        subcategory: [
          {
            id: 1,
            title: "Something",
            Icon: FaRegUser,
            textColor: undefined,
            backgroundColor: undefined,
            iconColor: IconColors.ERROR,
            url: "/purchase/suppliers/something",
            subcategory: undefined,
          },
        ],
      },
      {
        id: 2,
        title: "Create Voucher",
        Icon: FaFileInvoice,
        textColor: undefined,
        backgroundColor: undefined,
        iconColor: IconColors.ERROR,
        url: "/purchase/createVoucher",
        subcategory: undefined,
      },
      {
        id: 3,
        title: "Vouchers",
        Icon: FaFileInvoice,
        textColor: undefined,
        backgroundColor: undefined,
        iconColor: IconColors.SUCCESS,
        url: "/purchase/vouchers",
        subcategory: undefined,
      },
    ],
  },
  {
    id: 2,
    title: "Inventory",
    Icon: FaWarehouse,
    textColor: undefined,
    backgroundColor: undefined,
    iconColor: IconColors.ERROR,
    url: "/inventory",
    subcategory: undefined,
  },
  {
    id: 3,
    title: "Price",
    Icon: FaDollarSign,
    textColor: undefined,
    backgroundColor: undefined,
    iconColor: IconColors.INFO,
    url: "/price",
    subcategory: undefined,
  },
  {
    id: 4,
    title: "Sales",
    Icon: FaChartLine,
    textColor: undefined,
    backgroundColor: undefined,
    iconColor: IconColors.PRIMARY,
    url: "/sales",
    subcategory: undefined,
  },
  {
    id: 5,
    title: "Reports",
    Icon: FaClipboardList,
    textColor: undefined,
    backgroundColor: undefined,
    iconColor: IconColors.WARNING,
    url: "/reports",
    subcategory: undefined,
  },
  {
    id: 6,
    title: "Cash Book",
    Icon: FaWallet,
    textColor: undefined,
    backgroundColor: undefined,
    iconColor: IconColors.PRIMARY,
    url: "/cashBook",
    subcategory: undefined,
  },
  {
    id: 7,
    title: "Login",
    Icon: FaRegUserCircle,
    textColor: undefined,
    backgroundColor: undefined,
    iconColor: IconColors.PRIMARY,
    url: "/login",
    subcategory: undefined,
  },
  {
    id: 8,
    title: "Signup",
    Icon: FaRegUserCircle,
    textColor: undefined,
    backgroundColor: undefined,
    iconColor: IconColors.SECONDARY,
    url: "/signup",
    subcategory: undefined,
  },
];
